version: '3.1'

services:
  wordpress:
    container_name: WP-AP
    image: wordpress:latest
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - ./wordpress_data:/var/www/html
    networks:
      net-app:
        ipv4_address: 192.168.2.6  

  db:
    container_name: WP-BD
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_ROOT_PASSWORD: somerootpassword
    volumes:
      - ./db_data:/var/lib/mysql
    networks:
      net-app:
        ipv4_address: 192.168.2.7  

networks:
  net-app:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.2.0/24